id: 14aabbc8-d331-482e-89a9-15289a231ec1
name: supers-sentry-evidence-to-delivery
tags: {}
jobs:
  - name: main
    description: Main job (edit or replace)
    steps:
      - name: example
        description: Example step (edit or replace)
        task:
          type: model_method
          modelIdOrName: example-model
          methodName: run
        dependsOn: []
        weight: 0
        allowFailure: false
    dependsOn: []
    weight: 0
version: 1
