/**
 * Bundled audio assets (ADR-0033 §7) — the audio analog of
 * `substrate-textures.ts`. Samples ship as Vite-imported WAVs, so the bytes
 * are in the build and decode is deterministic: no network, no cache
 * variance; the offline export mix reads identical samples every run. The
 * Foley cues are checked-in renders generated by
 * `scripts/gen-foley-sounds.mjs`; runtime synthesis would violate the
 * byte-stable preview/export contract because Foley's noise and room impulse
 * generation use randomness.
 */
import type { CueName } from '@foleyjs/core';

import bedAmbientTextureUrl from '$lib/assets/sounds/bed-ambient-texture.wav';
import messagePopUrl from '$lib/assets/sounds/message-pop.wav';
import messageSendUrl from '$lib/assets/sounds/message-send.wav';
import tapbackDislikeUrl from '$lib/assets/sounds/tapback-dislike.wav';
import tapbackEmphasizeUrl from '$lib/assets/sounds/tapback-emphasize.wav';
import tapbackHahaUrl from '$lib/assets/sounds/tapback-haha.wav';
import tapbackHeartUrl from '$lib/assets/sounds/tapback-heart.wav';
import tapbackLikeUrl from '$lib/assets/sounds/tapback-like.wav';
import tapbackQuestionUrl from '$lib/assets/sounds/tapback-question.wav';

import { DEFAULT_EVENT_SAMPLES, MESSAGE_SAMPLES, TAPBACK_SAMPLES } from './sound-cues.ts';

export const FOLEY_CUE_NAMES = [
	'tick',
	'hover',
	'glide',
	'pop',
	'press',
	'release',
	'tap',
	'thock',
	'on',
	'off',
	'switch',
	'latch',
	'success',
	'error',
	'warning',
	'denied',
	'chime',
	'ping',
	'bell',
	'bubble',
	'swoosh',
	'whoosh',
	'drop',
	'rise',
	'loading',
	'ready',
	'complete',
	'sparkle'
] as const satisfies readonly CueName[];

export type FoleySoundSlug = `foley-${CueName}`;

export const FOLEY_SOUND_SLUGS: readonly FoleySoundSlug[] = FOLEY_CUE_NAMES.map(
	(cue): FoleySoundSlug => `foley-${cue}`
);

const foleySoundUrls = import.meta.glob<string>('../assets/sounds/foley/*.wav', {
	eager: true,
	query: '?url',
	import: 'default'
});

const FOLEY_SOUND_ASSETS = Object.fromEntries(
	FOLEY_CUE_NAMES.map((cue) => [
		`foley-${cue}`,
		foleySoundUrls[`../assets/sounds/foley/${cue}.wav`] ?? ''
	])
) as Record<FoleySoundSlug, string>;

const SOUND_ASSETS: Record<string, string> = {
	...FOLEY_SOUND_ASSETS,
	// Locked iMessage signature samples (provenance + ⚠ redistribution note in
	// Apple Messages recordings at Scott's direction — see 634d0d6/e222fad)
	'message-pop': messagePopUrl,
	'message-send': messageSendUrl,
	// Tapback acknowledgements, one per reaction type — Apple ToneLibrary
	// recordings, same ⚠ NOT-redistributable provenance as the pair above.
	// Locked-specific by the iMessage derivation (ADR-0033 §5 signature sound).
	'tapback-heart': tapbackHeartUrl,
	'tapback-like': tapbackLikeUrl,
	'tapback-dislike': tapbackDislikeUrl,
	'tapback-haha': tapbackHahaUrl,
	'tapback-emphasize': tapbackEmphasizeUrl,
	'tapback-question': tapbackQuestionUrl,
	// Ambient bed texture for full-frame pieces — referenced by audioCues, not a kit.
	'bed-ambient-texture': bedAmbientTextureUrl
};

// User compositions can persist a direct sample lock. Retired Legacy Supers
// sample slugs therefore remain loadable aliases, but are no longer listed in
// authoring UI or backed by separate WAV files.
const LEGACY_SOUND_ALIASES: Record<string, FoleySoundSlug> = {
	'core-whoosh-in': 'foley-swoosh',
	'core-whoosh-out': 'foley-whoosh',
	'core-impact': 'foley-drop',
	'core-tick': 'foley-tick',
	'core-click': 'foley-tap',
	'core-pop': 'foley-pop',
	'core-swipe': 'foley-whoosh',
	'core-scratch': 'foley-glide',
	'core-sub-drop': 'foley-latch',
	'core-sting': 'foley-complete',
	'thud-solid': 'foley-drop',
	'thud-felt': 'foley-press',
	'thud-deep': 'foley-denied',
	'fwip-in': 'foley-swoosh',
	'fwip-out': 'foley-whoosh',
	'fwip-soft-in': 'foley-glide',
	'fwip-soft-out': 'foley-glide',
	'pop-chip': 'foley-pop',
	'pop-round': 'foley-bubble',
	'tick-soft': 'foley-tick',
	'tick-snap': 'foley-switch',
	'click-thock': 'foley-thock',
	'draw-slide': 'foley-rise',
	'swish-send': 'foley-swoosh',
	'quick-whoosh-in': 'foley-swoosh',
	'quick-whoosh-out': 'foley-whoosh',
	'impact-book': 'foley-drop',
	'tick-pencil': 'foley-tick',
	'marker-swipe': 'foley-whoosh',
	'pencil-stroke': 'foley-glide'
};

function canonicalSoundSlug(slug: string): string {
	return LEGACY_SOUND_ALIASES[slug] ?? slug;
}

export function isSoundAsset(slug: string): boolean {
	return canonicalSoundSlug(slug) in SOUND_ASSETS;
}

export function listSoundAssets(): readonly string[] {
	return [...FOLEY_SOUND_SLUGS, 'bed-ambient-texture'];
}

// Fetch + decode is async and memoised per (slug, sample-rate) so each asset
// decodes once per rate — `decodeAudioData` resamples to the decoding
// context's rate, and preview (AudioContext) and export (OfflineAudioContext
// at the muxer's rate) may differ.
const bufferCache = new Map<string, Promise<AudioBuffer>>();

export function loadSoundBuffer(
	slug: string,
	context: BaseAudioContext
): Promise<AudioBuffer> | null {
	if (typeof window === 'undefined') return null;
	const canonicalSlug = canonicalSoundSlug(slug);
	const url = SOUND_ASSETS[canonicalSlug];
	if (!url) return null;
	const key = `${canonicalSlug}@${context.sampleRate}`;
	let pending = bufferCache.get(key);
	if (!pending) {
		pending = fetch(url)
			.then((response) => response.arrayBuffer())
			.then((bytes) => context.decodeAudioData(bytes));
		bufferCache.set(key, pending);
	}
	return pending;
}

/**
 * Boot gate (the ADR-0019 pattern): every engine-default sample — per event
 * and per tapback type — must be a bundled asset. Throws an aggregated Error
 * so a missing WAV fails at startup, not mid-export.
 */
export function assertSoundRegistryValid(): void {
	const problems = [
		...FOLEY_CUE_NAMES.flatMap((cue) =>
			FOLEY_SOUND_ASSETS[`foley-${cue}`] ? [] : [`Foley cue "${cue}" has no generated WAV asset`]
		),
		...Object.entries(DEFAULT_EVENT_SAMPLES).flatMap(([event, slug]) =>
			isSoundAsset(slug)
				? []
				: [`default sample for event "${event}" names unknown asset "${slug}"`]
		),
		...Object.entries(MESSAGE_SAMPLES).flatMap(([direction, slug]) =>
			isSoundAsset(slug) ? [] : [`iMessage ${direction} sample names unknown asset "${slug}"`]
		),
		...Object.entries(TAPBACK_SAMPLES).flatMap(([tapback, slug]) =>
			isSoundAsset(slug) ? [] : [`tapback "${tapback}" names unknown asset "${slug}"`]
		),
		...Object.entries(LEGACY_SOUND_ALIASES).flatMap(([legacySlug, replacementSlug]) =>
			SOUND_ASSETS[replacementSlug]
				? []
				: [`legacy sample "${legacySlug}" aliases missing asset "${replacementSlug}"`]
		)
	];
	if (problems.length > 0) {
		throw new Error(`Sound registry invalid:\n- ${problems.join('\n- ')}`);
	}
}
