import { z } from 'zod';

import compositionPosterManifest from '$lib/assets/composition-posters/manifest.json';

/**
 * The committed posters of the library: one rendered still per catalogued
 * Preset, generated by `pnpm capture:posters`
 * (`scripts/cdp-capture-composition-posters.ts`) and shipped with the app, so
 * every origin — the local build and the hosted one that keeps nothing — shows
 * each composition as itself ([ADR-0061](../../../docs/adr/0061-committed-composition-posters.md)).
 *
 * Each manifest row records the content key its still was rendered from. A
 * row whose key no longer matches the Preset is stale: the library falls back
 * to the Surface default for that card, and `composition-posters.test.ts`
 * fails until the poster is regenerated, so a stale still can never land.
 */

const CommittedCompositionPosterSchema = z.object({
	/** `posterKeyForPreset` of the Preset the still was rendered from. */
	contentKey: z.string().regex(/^[a-f0-9]{8,32}$/),
	/** Where the playhead stood when the still was taken. */
	timestampSeconds: z.number().nonnegative(),
	width: z.number().int().positive(),
	height: z.number().int().positive(),
	/** Share of the still's pixels that carry content, as measured when it was chosen. */
	contentFraction: z.number().min(0).max(1)
});

export type CommittedCompositionPoster = z.infer<typeof CommittedCompositionPosterSchema>;

/** Every committed poster by Preset slug, in the manifest's (sorted) order. */
export const COMMITTED_COMPOSITION_POSTERS: Readonly<Record<string, CommittedCompositionPoster>> = z
	.record(z.string(), CommittedCompositionPosterSchema)
	.parse(compositionPosterManifest);

// The stills themselves, addressed by Vite so each ships content-hashed and
// cache-immutable. `?no-inline` keeps a small still a file rather than a
// base64 data URL, which would otherwise ride inside every home-page load.
// Keyed by slug from the file name.
const posterAssetUrls = import.meta.glob<string>('$lib/assets/composition-posters/*.webp', {
	eager: true,
	query: '?no-inline',
	import: 'default'
});

const COMMITTED_POSTER_URL_BY_SLUG: ReadonlyMap<string, string> = new Map(
	Object.entries(posterAssetUrls).map(([path, url]) => [
		path.slice(path.lastIndexOf('/') + 1, -'.webp'.length),
		url
	])
);

/** Slugs that have a committed still on disk, whether or not the manifest still claims them. */
export function listCommittedPosterAssetSlugs(): readonly string[] {
	return [...COMMITTED_POSTER_URL_BY_SLUG.keys()].sort();
}

/**
 * The URL of a Preset's committed poster, or null when there is none for this
 * exact content — the card then shows its Surface default.
 */
export function committedCompositionPosterUrl(slug: string, contentKey: string): string | null {
	const entry = COMMITTED_COMPOSITION_POSTERS[slug];
	if (!entry || entry.contentKey !== contentKey) return null;
	return COMMITTED_POSTER_URL_BY_SLUG.get(slug) ?? null;
}
