import { hashObject } from '$lib/utils/object';

import type { Preset } from './engine-schema';
import { presetToWireFormat } from './preset-pure';

/**
 * Posters: a rendered still of a composition, used as its library-card
 * preview. Every poster is keyed by a content hash of the composition, so a
 * poster can never describe a composition other than the one it was rendered
 * from ([ADR-0061](../../../docs/adr/0061-committed-composition-posters.md)).
 *
 * Library Presets carry committed posters (`./composition-posters.ts`),
 * generated by `pnpm capture:posters` and shipped with the app on every
 * origin. User compositions, which live in a development-only store, are
 * captured on view through this module and kept in that store's `.posters/`
 * cache (`src/routes/api/posters/[key]/+server.ts`).
 */

/** One candidate poster frame, photographed and measured by the open Workspace. */
export interface ScriptedPosterFrameCapture {
	/** Where the playhead actually landed after the seek was clamped to the run. */
	timestampSeconds: number;
	width: number;
	height: number;
	/** Share of pixels differing from the frame's first pixel — the visible content, 0–1. */
	contentFraction: number;
	/** Every pixel identical: the frame renders nothing at all. */
	isBlank: boolean;
	/** The poster-sized WebP still, base64 so it crosses the CDP boundary as one string. */
	webpBase64: string;
}

declare global {
	interface Window {
		/**
		 * Workspace-bound poster seam, peer to `__gfxTimeline` and `__gfxExport`:
		 * park the playhead at a timestamp, settle the composite, and hand back the
		 * poster-sized still with its measurement. Driven only by
		 * `scripts/cdp-capture-composition-posters.ts`; never a UI path.
		 */
		__gfxCapturePosterFrameAt?: (
			timestampSeconds: number
		) => Promise<ScriptedPosterFrameCapture | null>;
	}
}

const API_BASE = '/api/posters';

/** Content key for a preset's poster — changes when the composition changes. */
export function posterKeyForPreset(preset: Preset): string {
	return hashObject(presetToWireFormat(preset));
}

/** URL the GET route serves a User composition's cached poster from (404 until captured). */
export function posterUrl(key: string): string {
	return `${API_BASE}/${key}`;
}

/** Whether a poster already exists (HEAD is derived from GET by SvelteKit). */
export async function posterExists(key: string): Promise<boolean> {
	try {
		const res = await fetch(`${API_BASE}/${key}`, { method: 'HEAD' });
		return res.ok;
	} catch {
		return false;
	}
}

/** Store a freshly-rendered poster blob under its content key. */
export async function putPoster(key: string, blob: Blob): Promise<void> {
	const res = await fetch(`${API_BASE}/${key}`, {
		method: 'PUT',
		headers: { 'Content-Type': 'image/webp' },
		body: blob
	});
	if (!res.ok) throw new Error(`Failed to store poster ${key}: ${res.statusText}`);
}
